name: Testing
on: push

jobs:
  test_project:
    runs-on: windows10
    steps:
    - uses: action/checkout@v2
    - name: Rub Django unit test
      run:
        pip3 install --user django
        python3 manage.py test